# Generated by Django 4.2.2 on 2024-05-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abastecimiento',
            fields=[
                ('id_abastecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id_preg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_preg', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=50)),
                ('direccion_prov', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('teléfono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut_usu', models.CharField(max_length=60)),
                ('nombre_usu', models.CharField(max_length=60)),
                ('correo_usu', models.CharField(max_length=60)),
                ('direccion_usu', models.CharField(max_length=60)),
                ('telefono_usu', models.IntegerField()),
                ('id_preg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pag.pregunta')),
                ('rol_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pag.rol')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre_prod', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=70)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pag.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_carrito',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pag.carrito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pag.producto')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_abastecimiento',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_abastecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pag.abastecimiento')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pag.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pag.usuario'),
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pag.proveedor'),
        ),
    ]
