# Generated by Django 4.2.2 on 2024-05-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='teléfono',
            new_name='telefono',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nombre_preg',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=40),
        ),
    ]
