# Generated by Django 4.2.2 on 2024-07-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pag', '0003_usuario_contrasena_usu'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('integrante_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_integrante_1', to='Pag.usuario')),
                ('integrante_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_integrante_2', to='Pag.usuario')),
                ('integrante_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_integrante_3', to='Pag.usuario')),
                ('lider_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lidera_proyecto', to='Pag.usuario')),
            ],
        ),
    ]
